version: "3.8"

services:
  core:
    user: root

    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
        - ../:/home/Challenger/
    ports:
        - 8888:8888
    restart: unless-stopped
